### ISSUE TITLE
Inability to translate correctly into languages with different forms of the word

### ISSUE THREAD

**Issue by aratakileo** [woodiertexas/architecture-extensions#45]
### Describe the bug

The built-up translation system is not suitable for translation into other languages, such as German, Ukrainian, Russian, in which the form of both the noun and dependent words may vary depending on the case of the noun and other factors. In such languages, it would be wrong to compose the name of the subject according to the scheme: what the block is made of + the name of the block.

An excellent solution to this problem would be to add the possibility of naming each block individually, as an addition to the current system

### Which side have you encountered the bug on?

Both

**Comment by falkreon** [comment]
Fixed in #43
In the F3+H advanced tooltip, if the ID displayed is `architecture_extensions:minecraft/stone_round_arch`, then its "override" localization key is the key Minecraft would normally make for it: `block.architecture_extensions.minecraft.stone_round_arch`

Note that serverside mods like Polydex are unable to see that these "override" localization keys exist, and will fallback to the less-intelligent system.

**Comment by aratakileo** [comment]
Thanks for the help
